/**
 * types 命名规范
 * 1. 模块的 type 以模块名开头
 * 2. 使用常量定义。变量名全部大写
 */

// 公有池表格
export const OPEN_TABLE_LIST_SELECT_CHANGE = 'open/OPEN_TABLE_LIST_SELECT_CHANGE'
export const OPEN_TABLE_LIST_TYPE = 'open/OPEN_TABLE_LIST_TYPE'
export const OPEN_TABLE_LIST_STATE = 'open/OPEN_TABLE_LIST_STATE'
export const OPEN_TABLE_LIST_AUTHORITY = 'open/OPEN_TABLE_LIST_AUTHORITY'
export const OPEN_TABLE_CHOOSED_LIST_CHANGE = 'open/OPEN_TABLE_CHOOSED_LIST_CHANGE'
export const OPEN_TABLE_PAGE_CHANGE = 'open/OPEN_TABLE_PAGE_CHANGE'
export const OPEN_TABLE_TOTALPAGE_CHANGE = 'open/OPEN_TABLE_TOTALPAGE_CHANGE'
export const OPEN_TABLE_CHANGE = 'open/OPEN_TABLE_CHANGE'
export const OPEN_TABLE_OPTIONS = 'openList/types.OPEN_TABLE_OPTIONS'
export const OPEN_TABLE_OPTIONS_SELECTED ='openList/OPEN_TABLE_OPTIONS_SELECTED'

export const OPEN_TABLE_HEAD_STATE_CHANGE = 'open/OPEN_TABLE_HEAD_STATE_CHANGE'
export const OPEN_TABLE_HEAD_TABLE_CHANGE = 'open/OPEN_TABLE_HEAD_TABLE_CHANGE'
export const OPEN_TABLE_HEAD_LIST_CHANGE = 'open/OPEN_TABLE_HEAD_LIST_CHANGE'

// 站内信
export const STATIONMAIL_IS_OUT = 'STATIONMAIL_IS_OUT'

// 属性下拉框
export const GROUP_COMPLEXDROP_DATA_PREP = 'GROUP_COMPLEXDROP_DATA_PREP'

