/**
 * types 命名规范
 * 1. 模块的 type 以模块名开头
 * 2. 使用常量定义。变量名全部大写
 */

// 全局
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const CHANGE_ACTIVE_MENU = 'CHANGE_ACTIVE_MENU'
export const GET_PLATFORMS = 'GET_PLATFORMS'
export const SCREEN_WIDTH = 'SCREEN_WIDTH'

// 投放管理
export const DELIVERY_LIST_LOADING = 'delivery/DELIVERY_LIST_LOADING'
export const DELIVERY_LIST_QUERYFORM = 'delivery/DELIVERY_LIST_QUERYFORM'
export const DELIVERY_LIST_TABLE = 'delivery/DELIVERY_LIST_TABLE'

export const DELIVERY_MONITOR_BASEINFO = 'delivery/DELIVERY_MONITOR_BASEINFO'
export const DELIVERY_MONITOR_ACCOUNT = 'delivery/DELIVERY_MONITOR_ACCOUNT'
export const DELIVERY_MONITOR_UPDATE_ACCOUNT_MONITORURL = 'delivery/DELIVERY_MONITOR_UPDATE_ACCOUNT_MONITORURL'
export const DELIVERY_MONITOR_ORDER = 'delivery/DELIVERY_MONITOR_ORDER'
export const DELIVERY_MONITOR_ORDER_QUERYFORM = 'delivery/DELIVERY_MONITOR_ORDER_QUERYFORM'
export const DELIVERY_MONITOR_UPDATE_ORDER_MONITORURL = 'delivery/DELIVERY_MONITOR_UPDATE_ORDER_MONITORURL'

export const DELIVERY_TEST_REPORT_FORM = 'delivery/DELIVERY_TEST_REPORT_FORM'
export const DELIVERY_TEST_LIST_LOADING = 'delivery/DELIVERY_TEST_LIST_LOADING'
export const DELIVERY_TEST_LIST_TABLE = 'delivery/DELIVERY_TEST_LIST_TABLE'
export const DELIVERY_TEST_LIST_FORM = 'delivery/DELIVERY_TEST_LIST_FORM'

// 订单管理
export const ORDER_LIST_LOADING = 'delivery/ORDER_LIST_LOADING'
export const ORDER_LIST_QUERYFORM = 'delivery/ORDER_LIST_QUERYFORM'
export const ORDER_LIST_TABLE = 'delivery/ORDER_LIST_TABLE'

// 客户管理
export const CUSTOM_LIST_USER = 'delivery/CUSTOM_LIST_USER'
export const CUSTOM_LIST_LOADING = 'delivery/CUSTOM_LIST_LOADING'
export const CUSTOM_LIST_TABLE = 'delivery/CUSTOM_LIST_TABLE'
export const CUSTOM_LIST_UPDATE_TABLE_APTITUDE = 'delivery/CUSTOM_LIST_UPDATE_TABLE_APTITUDE'
export const CUSTOM_LIST_QUERYFORM = 'delivery/CUSTOM_LIST_QUERYFORM'
export const CUSTOM_LIST_CUSTOMTABLE_MODAL = 'delivery/CUSTOM_LIST_CUSTOMTABLE_MODAL'
export const CUSTOM_LIST_STATUS_MODAL = 'delivery/CUSTOM_LIST_STATUS_MODAL'

export const CUSTOM_CREATE_BASE_FORM = 'delivery/CUSTOM_CREATE_BASE_FORM'
