/**
 * types 命名规范
 * 1. 模块的 type 以模块名开头
 * 2. 使用常量定义。变量名全部大写
 */
// 公共部分
export const HEADER_MEANSDATA = 'HEADER_MEANSDATA'

// 公有池
export const COMMON_TABLE_CHOOSED_LIST_CHANGE = 'common/COMMON_TABLE_CHOOSED_LIST_CHANGE'
export const COMMON_TABLE_PAGE_CHANGE = 'common/COMMON_TABLE_PAGE_CHANGE'
export const COMMON_TABLE_SEARCH_LIST = 'common/COMMON_TABLE_SEARCH_LIST'
export const COMMON_TABLE_SEARCH_LIST_CHOOSE = 'common/COMMON_TABLE_SEARCH_LIST_CHOOSE'
export const COMMON_TABLE_GET_POOLLIST = 'common/COMMON_TABLE_GET_POOLLIST'
export const COMMON_TABLE_CHANGE_POOLLIST_VALUE = 'common/COMMON_TABLE_CHANGE_POOLLIST_VALUE'
export const COMMON_TABLE_CHANGE = 'common/COMMON_TABLE_CHANGE'
export const COMMON_TABLE_GET_TRADE_LIST = 'common/COMMON_TABLE_GET_TRADE_LIST'
export const CHOOSE_SEARCHLIST_CITYNAME = 'common/CHOOSE_SEARCHLIST_CITYNAME'
export const COMMON_TABLE_DELETE_CITYCODE = 'common/COMMON_TABLE_DELETE_CITYCODE'


// 私人池
export const PRIVATE_TABLE_CHOOSED_LIST_CHANGE = 'private/PRIVATE_TABLE_CHOOSED_LIST_CHANGE'
export const PRIVATE_TABLE_PAGE_CHANGE = 'private/PRIVATE_TABLE_PAGE_CHANGE'
export const PRIVATE_TABLE_SEARCH_LIST = 'private/PRIVATE_TABLE_SEARCH_LIST'
export const PRIVATE_TABLE_SEARCH_LIST_CHOOSE = 'private/PRIVATE_TABLE_SEARCH_LIST_CHOOSE'
export const PRIVATE_TABLE_CHANG = 'private/PRIVATE_TABLE_CHANG'

// 站内信
export const STATIONMAIL_IS_OUT = 'STATIONMAIL_IS_OUT'

// 属性下拉框
export const GROUP_COMPLEXDROP_DATA_PREP = 'GROUP_COMPLEXDROP_DATA_PREP'


